### ISSUE TITLE
Getting empty file

### ISSUE THREAD

**Issue by rikonor** [krolaw/zipstream#1]
Hi,

I came into a situation where I needed to read a zip file from an io.Reader and saw that you had the same issue and wrote this lib to solve it. I was able to use your library, however, when I try to use it with a helper function that I wrote (which just mocks a zip file in a bytes.Buffer) I am failing to read from the zip file.

Not sure whether you're maintaining this or not but here is the code reproducing my issue:
https://play.golang.org/p/nKUpO_nZQz

Thanks!

**Comment by krolaw** [comment]
Hi,

Thank you for taking an interest in my library.  I copied the bytes from zip.NewWriter to a file and it also failed.  It would appear that there is a difference between the outputs of the zip application and the zip go library.  This is most certainly a bug/limitation my end, which will need analysis and repair.

In the meantime, you will have to get the zip app to create the data you need to stream, or wait, or fix :-)

**Comment by krolaw** [comment]
Looks like descriptorReader has a bug.  Must sleep now, but hopefully sort tomorrow evening.

**Comment by rikonor** [comment]
Thanks @krolaw! Tested and works.
