### ISSUE TITLE
Panic reading zip

### ISSUE THREAD

**Issue by rikonor** [krolaw/zipstream#2]
Hi,

Been getting a panic with a specific file.

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x105480, 0xc82000a0c0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/krolaw/zipstream.(*descriptorReader).Read(0xc820012220, 0xc82007c000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
        /Users/orrikon/workspace/go/src/github.com/krolaw/zipstream/descriptor.go:49 +0x959
```

Can I email you the file?

**Comment by krolaw** [comment]
I'm sorry that you are the tester for these type of valid zip files.  I will look at it tonight.  I suspect changing line 43 of descriptor to: `i := bytes.Index(z[s:len(z)-4], sigBytes) + s`
may fix your problem.

**Comment by rikonor** [comment]
@krolaw Thanks!
