### ISSUE TITLE
usage with data descriptor record types

### ISSUE THREAD

**Issue by sigmonsays** [krolaw/zipstream#4]
Trying to use this library to read a stream of zip files and am encounting an issue with zip files with a data descriptor record.

I have added logging into the example code for the Next method and it is discarding the entire file. I only receive the first file and the remaining content of the stream is discarded due to line 40 [1]

Does this library require the local header having compressed size and uncompressed size set?

It appears to have code for handling the data descriptor but even the unit tests discard the file contents and this results in a unusable library.

[1] https://github.com/krolaw/zipstream/blob/master/reader.go#L40

**Comment by krolaw** [comment]
That does seem strange. I'll try to have a look at it tonight.

**Comment by sigmonsays** [comment]
pardon the blatant paste but here is the data i'm sending as a chunked transfer encoding. I hope its obvious what zip data is being sent.
<pre>
Sending file ./testdata/small1/a.txt
send: '23'
send: '\r\n'
send: 'PK\x03\x04\x14\x00\x08\x00\x00\x002\x8e\xd2L\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00a.txt'
send: '\r\n'
send: '2'
send: '\r\n'
send: 'a\n'
send: '\r\n'
send: '10'
send: '\r\n'
send: 'PK\x07\x08\x07\xa1\xea\xdd\x02\x00\x00\x00\x02\x00\x00\x00'
send: '\r\n'

Sending file ./testdata/small1/b.txt
send: '23'
send: '\r\n'
send: 'PK\x03\x04\x14\x00\x08\x00\x00\x000\x8e\xd2L\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00b.txt'
send: '\r\n'
send: '2'
send: '\r\n'
send: 'b\n'
send: '\r\n'
send: '10'
send: '\r\n'
send: 'PK\x07\x08\xc4\xf2\xc7\xf6\x02\x00\x00\x00\x02\x00\x00\x00'
send: '\r\n'
send: '0\r\n\r\n'
</pre>

**Comment by krolaw** [comment]
The problem is that zipstream uses a buffered reader, so it reads beyond the end of the zip file. These bytes need to be recovered and fed back into the stream so they can be read by the following reader. Added Buffered() to allow recovery and updated test to include multi zip file stream.

**Comment by sigmonsays** [comment]
So the reader is only capable of handling a single file in a zip archive?

It seems like this functionality should be included in the library so the client doesn't have to concern itself with checking Bufferered() and feeding it back in. I'll take a look shortly and see what I can figure out.

**Comment by krolaw** [comment]
Ideally, reader would take a *bufio.Reader (not io.Reader) and use it instead of creating its own. That way it wouldn't read beyond the end of the zip file, negating the need for the Buffered method. This would be a breaking change, so it's something I'll look at once vgo settles.

What's the reasoning behind not having all the files in the single zip?

**Comment by krolaw** [comment]
My mistake. You don't need to call Buffered. Just call Next after it returns io.EOF and it will start processing the following zip file. So just one Reader. The tricky bit if using this technique, is knowing when to stop. One way is to check if you get no files between two io.EOFs.
